# Generated by Django 6.0.5 on 2026-05-10 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(blank=True, max_length=11)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('aliases', models.TextField(blank=True, help_text='Palabras clave separadas por coma para búsqueda en chat IA')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('incompleto', 'Incompleto')], default='activo', max_length=15)),
                ('stock_minimo', models.PositiveIntegerField(default=0, help_text='En unidades base')),
                ('permite_fraccion', models.BooleanField(default=False)),
                ('es_transformacion', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.marca')),
            ],
            options={
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Unidad, Docena, Caja x5 doc', max_length=100)),
                ('unidades_base', models.PositiveIntegerField(help_text='Cuántas unidades base equivale esta presentación')),
                ('es_base', models.BooleanField(default=False, help_text='Es la unidad mínima de venta')),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='productos.producto')),
            ],
            options={
                'db_table': 'producto_presentaciones',
                'ordering': ['unidades_base'],
                'unique_together': {('producto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_inicial', 'Stock Inicial'), ('compra', 'Compra'), ('venta', 'Venta'), ('devolucion_compra', 'Devolución Compra'), ('devolucion_venta', 'Devolución Venta'), ('transferencia_entrada', 'Transferencia Entrada'), ('transferencia_salida', 'Transferencia Salida'), ('ajuste', 'Ajuste Inventario'), ('transformacion_entrada', 'Transformación Entrada'), ('transformacion_salida', 'Transformación Salida')], max_length=30)),
                ('cantidad', models.IntegerField(help_text='Positivo=entrada, negativo=salida')),
                ('stock_resultante', models.IntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50)),
                ('nota', models.TextField(blank=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='productos.producto')),
            ],
            options={
                'db_table': 'kardex',
                'ordering': ['-registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='ProductoEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.etiqueta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'db_table': 'producto_etiquetas',
                'unique_together': {('producto', 'etiqueta')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, through='productos.ProductoEtiqueta', to='productos.etiqueta'),
        ),
        migrations.CreateModel(
            name='ProductoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='productos.producto')),
            ],
            options={
                'db_table': 'producto_fotos',
                'ordering': ['-es_principal', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ProductoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_minorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('presentacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precio', to='productos.presentacion')),
            ],
            options={
                'db_table': 'producto_precios',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='productos.categoria')),
            ],
            options={
                'db_table': 'subcategorias',
                'ordering': ['nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.subcategoria'),
        ),
        migrations.CreateModel(
            name='PrecioFraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mitad', 'Mitad'), ('cuarto', 'Cuarto')], max_length=10)),
                ('unidades_base', models.PositiveIntegerField(help_text='Unidades base que corresponden a esta fracción')),
                ('precio_minorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fracciones', to='productos.presentacion')),
            ],
            options={
                'db_table': 'producto_precio_fracciones',
                'unique_together': {('presentacion', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, help_text='En unidades base')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='core.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='productos.producto')),
            ],
            options={
                'db_table': 'inventario',
                'unique_together': {('producto', 'almacen')},
            },
        ),
        migrations.CreateModel(
            name='ProductoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='productos.producto')),
            ],
            options={
                'db_table': 'producto_campos',
                'unique_together': {('producto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='productos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.proveedor')),
            ],
            options={
                'db_table': 'producto_proveedor',
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
