# Generated by Django 6.0.5 on 2026-05-10 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('con_documento', 'Con Documento'), ('sin_documento', 'Sin Documento'), ('mercado', 'Mercado')], max_length=20)),
                ('fecha', models.DateField()),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('forma_pago', models.CharField(choices=[('caja', 'Caja del Negocio'), ('adelanto_dueno', 'Adelanto del Dueño'), ('combinado', 'Combinado')], default='caja', max_length=20)),
                ('monto_caja', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_adelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flete_proveedor', models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo que cobra el proveedor', max_digits=10)),
                ('precio_por_bulto', models.DecimalField(decimal_places=2, default=0, help_text='Precio por bulto de la agencia de transporte', max_digits=8)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='borrador', max_length=15)),
                ('nota', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.almacen')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.proveedor')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compras',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Para productos sin registrar aún', max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades_base_por_unidad', models.PositiveIntegerField(default=1, help_text='Cuántas unidades base trae cada unidad comprada')),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cajas_por_bulto', models.PositiveIntegerField(default=1, help_text='Cuántas unidades caben en un bulto para calcular flete agencia')),
                ('num_bultos', models.PositiveIntegerField(default=0)),
                ('flete_agencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flete_proveedor_proporcional', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('costo_directo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('costo_unitario_base', models.DecimalField(decimal_places=4, default=0, help_text='Costo directo por unidad base', max_digits=10)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'db_table': 'compra_items',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(db_column='almacen_destino_id', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrada', to='core.almacen')),
                ('almacen_origen', models.ForeignKey(db_column='almacen_origen_id', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salida', to='core.almacen')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transferencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades_base', models.IntegerField()),
                ('presentacion', models.ForeignKey(db_column='producto_precio_id', on_delete=django.db.models.deletion.PROTECT, to='productos.productoprecio')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.transferencia')),
            ],
            options={
                'db_table': 'transferencia_items',
            },
        ),
        migrations.CreateModel(
            name='StockInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='En unidades base')),
                ('costo_aproximado', models.DecimalField(decimal_places=4, default=0, help_text='Costo por unidad base aproximado', max_digits=10)),
                ('fecha', models.DateField()),
                ('aplicado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.proveedor')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_inicial',
            },
        ),
    ]
